### PR TITLE
Fix Abbasid landmark wing icons.

### PR DESCRIPTION
**Pull request by whorrified**

### CODE REVIEW

**Comment by whorrified** [comment]
Hi @jensbuehl,

Sorry, I had to re-create the PR since the commit wasn't signed before in #93.

**Comment by jensbuehl** [comment]
Great, thanks. Wanna exchange in the folder with the original size images as well to keep it consistent?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by whorrified** [comment]
Good catch, done.

**Review by jensbuehl — APPROVED** [review]
LGTM - thanks! :)

Maybe use develop branch next time which is deployed to a staging environment to run smoke tests.

**Pull request merged**
